// flow-typed signature: be93cb4348da175a0277487cdb97509c
// flow-typed version: <<STUB>>/react-smooth-collapse_v1.3.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-smooth-collapse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-smooth-collapse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-smooth-collapse/js/getTransitionTimeMs' {
  declare module.exports: any;
}

declare module 'react-smooth-collapse/js/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-smooth-collapse/js/getTransitionTimeMs.js' {
  declare module.exports: $Exports<'react-smooth-collapse/js/getTransitionTimeMs'>;
}
declare module 'react-smooth-collapse/js/index.js' {
  declare module.exports: $Exports<'react-smooth-collapse/js/index'>;
}
